/* cmxDeviceServicecdsObject.h
   Generated by gSOAP 2.7.6e from ds_intf.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef cmxDeviceServicecds_H
#define cmxDeviceServicecds_H
#include "cmxDeviceServiceH.h"
extern SOAP_NMAC struct Namespace cmxDeviceService_namespaces[];

namespace cmxDeviceService {
class cds : public soap
{    public:
	cds()
	{ soap_init(this); this->namespaces = cmxDeviceService_namespaces; };
	virtual ~cds() { soap_destroy(this); soap_end(this); soap_done(this); };
	virtual	int serve() { return cmxDeviceService_serve(this); };
};

} // namespace cmxDeviceService

#endif
