/* envClient.cpp
   Generated by gSOAP 2.7.6e from soap_lib/env.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "envH.h"

SOAP_SOURCE_STAMP("@(#) envClient.cpp ver 2.7.6e 2010-08-20 13:24:12 GMT")


/* End of envClient.cpp */
